#!/bin/bash

echo "Updating dotfiles"

cp -v ~/.bash_aliases $PWD/.bash_aliases
cp -v ~/.bash_profile $PWD/.bash_profile
cp -v ~/.bashrc $PWD/.bashrc
cp -v ~/.gitconfig $PWD/.gitconfig
cp -v ~/.gitignore $PWD/.gitignore
cp -v ~/.git $PWD/.git-scripts -r
cp -v  ~/.hidden $PWD/.hidden
cp -v ~/.nanorc $PWD/.nanorc
cp -v ~/.profile $PWD/.profile
cp -v ~/.tmux.conf $PWD/.tmux.conf
cp -v ~/.vimrc $PWD/.vimrc
cp -v ~/.zsh_aliases $PWD/.zsh_aliases
cp -v ~/.zshenv $PWD/.zshenv
cp -v ~/.zshrc $PWD/.zshrc
cp -v ~/.zsh_scripts $PWD/.zsh_scripts
cp -v ~/.screenrc $PWD/.screenrc
cp -v ~/.mongorc.js $PWD/.mongorc.js
cp -v ~/.cobra.yaml $PWD/.cobra.yaml
